# Generated by Django 2.1.2 on 2019-02-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activation1',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activation1',
        ),
    ]
